### ISSUE TITLE
Change name of device to Dock Pro?

### ISSUE THREAD

**Issue by rsampayo** [rsampayo/sleepme_thermostat#12]
Should we change the name of the device from SleepMe [Name of Device] to Dock Pro [Name of device]?
<img width="744" alt="Screenshot 2024-08-18 at 12 02 22 AM" src="https://github.com/user-attachments/assets/c784035e-12b8-401e-9d30-d0f00ed12016">

**Comment by mikesalz** [comment]
I agree.  I created a PR
https://github.com/rsampayo/sleepme_thermostat/pull/13

What is your preference?  Should I merge any changes I made or would you like to approve them first?

**Comment by rsampayo** [comment]
For now I think it would be better if I review it.

**Comment by mikesalz** [comment]
Sounds good.  I realized I missed a couple of places, so I'll be submitting another PR shortly
