### ISSUE TITLE
Undoing things by mistake.

### ISSUE THREAD

**Issue by rsampayo** [rsampayo/sleepme_thermostat#14]
@mikesalz, I forgot to pull your changes and I think I undid your fixes. (sorry!). I thinks its just the en.json and es.json.

**Comment by rsampayo** [comment]
Used to working alone :(

**Comment by mikesalz** [comment]
Yeah - I think maybe i was trying to resync my repo from yours and ended up just switching to yours.  Sorry about that.  But you should have my latest changes now, so you might want to pull changes again.

**Comment by rsampayo** [comment]
thanks
