### ISSUE TITLE
Refactor Update Process to Optimize API Calls and Improve Entity Management

### ISSUE THREAD

**Issue by rsampayo** [rsampayo/sleepme_thermostat#15]
Description:

The current update process is inefficient and leads to excessive API calls. Each entity triggers its own update, causing redundant requests and potential performance issues. There is a need to refactor this process to centralize update management, reduce API call frequency, and improve the handling of disconnected devices.

Proposed Solution:

	1.	Introduce a new UpdateManager:
	•	Create a centralized UpdateManager to handle all updates.
	•	The UpdateManager should trigger updates manually at a set interval (e.g., every 15 seconds) instead of allowing individual entities to initiate updates.
	2.	Optimize API Calls:
	•	By centralizing the update process, we can reduce the number of API calls, avoiding redundant requests and improving overall system performance.
	3.	Improve Entity Management:
	•	Update the logic to ensure that if a device is disconnected, its associated climate entity is marked as unavailable.
	•	Ensure proper classification of disconnected entities to improve the system’s representation of device connectivity.

Benefits:

	•	Performance Improvement: By reducing redundant API calls, the system will become more efficient, especially in environments with multiple devices.
	•	Better Device Management: Ensuring that entities accurately reflect device status (e.g., disconnected) will enhance the reliability of the system.
	•	Maintainability: Centralizing the update logic will simplify future updates and maintenance of the update process.

**Comment by rsampayo** [comment]
https://github.com/rsampayo/sleepme_thermostat/commit/cc1e19a7a408902fe1e9034c3c823d2a114027a5#diff-4c6fd56f18dfef1604d6a01e3653cba4b8f007c0353ccd706cd84e28a6ad3253
@mikesalz , this is a big change. A lot of things were moved around. Please help me with extensive testing. I would be surprised if it worked on the first try.

**Comment by mikesalz** [comment]
I can test it a little later.  Will I need to remove and re-add my devices?

**Comment by rsampayo** [comment]
There is no rush. Yeah, it would be better if you remove , restart, re-add.

**Comment by mikesalz** [comment]
It's looking good so far!  I changed Docker to Dock again and submitted a PR  =)

**Comment by rsampayo** [comment]
@mikesalz, I think you should revert to the previous version. This one is making too many api calls.

**Comment by rsampayo** [comment]
I pushed a fix.

**Comment by rsampayo** [comment]
I just realized I was running two instances of the integration.  One with an alpha version and I think that was the one that was using most of the api call. Let me know if you get 429 msg.

**Comment by mikesalz** [comment]
I haven't received any 429 errors.  Yesterday I did remove the separate rest sensors that I had previously created, just to be safe.  It looks like your latest change just updates the polling interval.  I might try leaving mine at 15 for now to see how it goes.  Do you think that should be configurable from the UI?  Not sure if it is worth the effort or not, but just throwing the idea out there.

As far as errors, the only thing I have in my logs is this, and it only occurred once since last evening.  Oddly, there was no request error value.

```
2024-08-19 01:33:09.100 ERROR (MainThread) [custom_components.sleepme_thermostat.sleepme] [Device zx-cdp37u96epuc70v4m8u0] Request error:
```

**Comment by rsampayo** [comment]
Thats good news. I think it was mostly my alpha version running on my other test rig. I did push an additional change to only retry PATCH call. (It doesnt make sense to retry an "update"  in 30 sec when there is a new one every 15 sec).  About letting the user configure the polling I think It would cause more trouble for the avg user. I think 15 sec is good enough (considering how strict the rate limiting policy is). Let me know how it works for you.  I got this error:

This error originated from a custom integration.

Logger: custom_components.sleepme_thermostat.update_manager
Source: helpers/update_coordinator.py:354
integration: SleepMe Dock Pro (documentation)
First occurred: 3:51:07 AM (1 occurrences)
Last logged: 3:51:07 AM

Unexpected error fetching SleepMe Update Manager zx-ca70fgqq3rsc70jr0kbg data
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
    resp = await self._pool.handle_async_request(req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
    raise exc from None
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
    response = await connection.handle_async_request(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
    return await self._connection.handle_async_request(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 143, in handle_async_request
    raise exc
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 113, in handle_async_request
    ) = await self._receive_response_headers(**kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 186, in _receive_response_headers
    event = await self._receive_event(timeout=timeout)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 224, in _receive_event
    data = await self._network_stream.read(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 32, in read
    with map_exceptions(exc_map):
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/local/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ReadTimeout

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sleepme_thermostat/update_manager.py", line 31, in _async_update_data
    device_info = await self.client.get_device_info()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/sleepme_thermostat/sleepme.py", line 120, in get_device_info
    response = await client.get(url, headers=headers)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1801, in get
    return await self.request(
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
    return await self.send(request, auth=auth, follow_redirects=follow_redirects)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
    response = await self._send_handling_auth(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
    response = await self._send_handling_redirects(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
    response = await self._send_single_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
    response = await transport.handle_async_request(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
    with map_httpcore_exceptions():
  File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
    self.gen.throw(value)
  File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
    raise mapped_exc(message) from exc
httpx.ReadTimeout

**Comment by mikesalz** [comment]
Hey @rsampayo!  For the most part the refactoring has worked very well.  I did find some errors in my logs this morning, though.  Pasting below.  Let me know if I can do anything to help.

> 
> 2024-08-20 07:10:19.138 ERROR (MainThread) [custom_components.sleepme_thermostat.update_manager] Error updating device data for zx-cdke5ghn4o7c70mv1khg: Server error '500 Internal Server Error' for url 'https://api.developer.sleep.me/v1/devices/zx-cdke5ghn4o7c70mv1khg'
> For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500
> 2024-08-20 07:10:19.138 ERROR (MainThread) [custom_components.sleepme_thermostat.update_manager] Unexpected error fetching SleepMe Update Manager zx-cdke5ghn4o7c70mv1khg data
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
> self.data = await self._async_update_data()
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/config/custom_components/sleepme_thermostat/update_manager.py", line 31, in _async_update_data
> device_info = await self.client.get_device_info()
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/config/custom_components/sleepme_thermostat/sleepme.py", line 124, in get_device_info
> response.raise_for_status() # Raise an exception for HTTP errors
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/httpx/_models.py", line 761, in raise_for_status
> raise HTTPStatusError(message, request=request, response=self)
> httpx.HTTPStatusError: Server error '500 Internal Server Error' for url 'https://api.developer.sleep.me/v1/devices/zx-cdke5ghn4o7c70mv1khg'
> For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500

------------------------------------------------------------------------------------------------

> 
> 2024-08-20 03:46:09.047 ERROR (MainThread) [custom_components.sleepme_thermostat.update_manager] Error updating device data for zx-cdke5ghn4o7c70mv1khg:
> 2024-08-20 03:46:09.048 ERROR (MainThread) [custom_components.sleepme_thermostat.update_manager] Unexpected error fetching SleepMe Update Manager zx-cdke5ghn4o7c70mv1khg data
> Traceback (most recent call last):
> File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
> yield
> File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
> resp = await self._pool.handle_async_request(req)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
> raise exc from None
> File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
> response = await connection.handle_async_request(
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
> return await self._connection.handle_async_request(request)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 143, in handle_async_request
> raise exc
> File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 113, in handle_async_request
> ) = await self._receive_response_headers(**kwargs)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 186, in _receive_response_headers
> event = await self._receive_event(timeout=timeout)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/httpcore/_async/http11.py", line 224, in _receive_event
> data = await self._network_stream.read(
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/httpcore/_backends/anyio.py", line 32, in read
> with map_exceptions(exc_map):
> File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
> self.gen.throw(value)
> File "/usr/local/lib/python3.12/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
> raise to_exc(exc) from exc
> httpcore.ReadTimeout
> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 354, in _async_refresh
> self.data = await self._async_update_data()
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/config/custom_components/sleepme_thermostat/update_manager.py", line 31, in _async_update_data
> device_info = await self.client.get_device_info()
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/config/custom_components/sleepme_thermostat/sleepme.py", line 123, in get_device_info
> response = await client.get(url, headers=headers)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1801, in get
> return await self.request(
> ^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1574, in request
> return await self.send(request, auth=auth, follow_redirects=follow_redirects)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1661, in send
> response = await self._send_handling_auth(
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
> response = await self._send_handling_redirects(
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
> response = await self._send_single_request(request)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/httpx/_client.py", line 1763, in _send_single_request
> response = await transport.handle_async_request(request)
> ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
> with map_httpcore_exceptions():
> File "/usr/local/lib/python3.12/contextlib.py", line 158, in __exit__
> self.gen.throw(value)
> File "/usr/local/lib/python3.12/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
> raise mapped_exc(message) from exc
> httpx.ReadTimeout

**Comment by mikesalz** [comment]
I just restarted HA and got this error.  With no details.

> 
2024-08-20 09:32:22.915 ERROR (MainThread) [custom_components.sleepme_thermostat.sleepme] [Device zx-cdke5ghn4o7c70mv1khg] Request error:

**Comment by rsampayo** [comment]
Im done with refactoring the API part of the code... for now.
