### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by mikesalz** [rsampayo/sleepme_thermostat#3]
Hi @rsampayo - So far this integration is working very well!  I have a few questions/suggestions.  I'm not going to pretend to know python very well, but if I am reading the code correctly it looks like the model and firmware version might be hard coded.  I am wondering if the API can be used to get that data?  There are some other informational fields available as well, like serial number, IP address, temperature unit, time zone, etc.  Those are really just "nice to haves" but wouldn't have any impact on functionality.

![image](https://github.com/user-attachments/assets/d4f4f476-f0c3-47d3-bf6f-ea8f76668129)

**Comment by rsampayo** [comment]
Hey Mike, I like your attention to detail. That's correct. They are only a placeholder. Let me see what I can do.

**Comment by rsampayo** [comment]
I am going to try to add Firmware, mac, model and serial number to the device info. And then I might add IP, LAN IP, is_connected, timezone, brightness_level and display_temp_unit a sensors in a Diagnostic seccion.

**Comment by mikesalz** [comment]
> I like your attention to detail

I think this translates to: I wish this guy would just leave me alone! :)

**Comment by rsampayo** [comment]
> > I like your attention to detail
> 
> I think this translates to: I wish this guy would just leave me alone! :)

Hahah, not at all. The complete opposite!  Keep them coming. Just help me out with the testing.

**Comment by mikesalz** [comment]
You got it!

**Comment by rsampayo** [comment]
Ok Mike, give it a go.

**Comment by mikesalz** [comment]
hmmm... I downloaded the current code, deleted my sleepme_thermostat folder from custom_components, and then copied the new folder into it and restarted HA.  Twice.  But none of the new info is showing.  I even verified that the values are in the python.  Interestingly, the model and firmware version are now completely gone from the Device Info section.

![image](https://github.com/user-attachments/assets/7bf52a1e-a97c-4046-818d-7604c0ec4932)

**Comment by rsampayo** [comment]
Can you delete your devices restart and re add. And turn on "debug log" and check the full log to see if you get errors.

**Comment by mikesalz** [comment]
Looking better!

![image](https://github.com/user-attachments/assets/67eb7b00-d902-4896-b0ab-bef7c16c7d4f)

**Comment by mikesalz** [comment]
Also - You may have already seen this in your research, but I found this page that discusses how to add logos.

https://developers.home-assistant.io/blog/2020/05/08/logos-custom-integrations/

**Comment by rsampayo** [comment]
> Also - You may have already seen this in your research, but I found this page that discusses how to add logos.
> 
> https://developers.home-assistant.io/blog/2020/05/08/logos-custom-integrations/

Thats great, do you think you could create the icons with the needed specs?

**Comment by mikesalz** [comment]
I can give it a shot over the weekend

**Comment by rsampayo** [comment]
> I can give it a shot over the weekend

Great, you pick the look.

**Comment by rsampayo** [comment]
I created an issue for the icon 
https://github.com/rsampayo/sleepme_thermostat/issues/2
