### ISSUE TITLE
Feature Request: Add Additional Sensors (IP Address, LAN Address, Connection Status, Timezone, Brightness Level, Display Temp Unit)

### ISSUE THREAD

**Issue by rsampayo** [rsampayo/sleepme_thermostat#5]
Feature Request:

As part of enhancing the sleepme_thermostat integration, I propose adding the following sensors to provide more detailed information and control within Home Assistant:

	1.	IP Address Sensor:
	•	Displays the current IP address of the Dock Pro device.
	2.	LAN Address Sensor:
	•	Shows the local network (LAN) address of the device.
	3.	Connection Status Sensor:
	•	Indicates whether the Dock Pro is currently connected to the network, represented as a binary sensor (connected/disconnected).
	4.	Timezone Sensor:
	•	Displays the timezone setting configured on the device.
	5.	Brightness Level Sensor:
	•	Monitors and displays the current brightness level of the device’s display.
	6.	Display Temperature Unit Sensor:
	•	Shows the temperature unit (Celsius/Fahrenheit) that the Dock Pro is currently using for display.

Rationale:
Adding these sensors will enhance the integration by providing users with more comprehensive data, allowing for better monitoring, automation, and troubleshooting of the Dock Pro system in Home Assistant.

Implementation Considerations:
These features can be integrated as part of the existing infrastructure for sensor data, ensuring compatibility and seamless updates for users.

**Comment by rsampayo** [comment]
@mikesalz ,I might have to do a big refactoring of how all the sensors would update to optimize API calls and not get throttled by the API limit.

**Comment by mikesalz** [comment]
Ok, thanks for the heads up

**Comment by mikesalz** [comment]
Are you concerned about getting blacklisted? Is there anything I should change on my end to prevent any issues?

**Comment by rsampayo** [comment]
No, its not that excessive but if you exceed the rate limit you start to see a considerable lag in your UI.

**Comment by rsampayo** [comment]
I just pushed a new version. I added the is_connected sensor. I hope I didn't break anything else. Im still working on the refactoring but It will move a lot of things (one of my defining characteristics, trying to fix something that isn't broken, breaking it then asking myself why im like that). Let me know if it works.

**Comment by rsampayo** [comment]
Add the sensors in https://github.com/rsampayo/sleepme_thermostat/releases/tag/v2.1.0
