### ISSUE TITLE
Config Flow: Token Input Field Missing Name Label

### ISSUE THREAD

**Issue by rsampayo** [rsampayo/sleepme_thermostat#6]
Issue:

During the configuration flow of the sleepme_thermostat integration, the input field for the user token does not display a name or label. This makes it unclear to users what information is required in that field.

Steps to Reproduce:

	1.	Begin the configuration process for the sleepme_thermostat integration in Home Assistant.
	2.	Reach the step where the user is prompted to enter their API token.
	3.	Observe that the input field for the token does not display a name or label, leaving users unsure of what to input.

Expected Behavior:
The input field should clearly display a label such as “API Token” to guide users in entering the correct information.

Actual Behavior:
The input field is blank, with no label indicating what the user should enter.

Impact:
This issue can lead to confusion and potential misconfiguration as users may not understand what is required in the unlabeled field.

Suggested Fix:
Update the configuration flow to include a label for the token input field, ensuring that users can easily identify what information is needed.

This enhancement will improve the user experience during the setup process, making it more intuitive and user-friendly.

**Comment by rsampayo** [comment]
I just pushed a new version. I added the strings.json in English and Spanish with this the name of the Token field should now be there along with titles and descriptions of the steps. Also fixed an issue when you put an invalid token. @Mike could you give it a test?

**Comment by mikesalz** [comment]
Hey @rsampayo!  It mostly looks good.  Except the name is now "Docker" rather than Dock. 

![image](https://github.com/user-attachments/assets/98f6f115-1b6b-4dc5-9460-0bcfed19d964)

**Comment by mikesalz** [comment]
One more thing.  I'm not sure if you have any control over this or not.  But it allows you to re-add the same Dock Pros that have already been added.  They show up with no devices.

![image](https://github.com/user-attachments/assets/f6660fce-9165-4a45-aec5-d9448c6f9e9c)

![image](https://github.com/user-attachments/assets/eef6c07a-a163-4125-9e82-c7e17fb3b7d4)

**Comment by rsampayo** [comment]
Hey @mikesalz, thanks for helping me out!  I invited you as a collaborator. Do you think you could help correct the "Docker" to "Dock" bug? That one is easy. Just edit the en.json and es.json files. You can do it in https://github.com/rsampayo/sleepme_thermostat/blob/main/custom_components/sleepme_thermostat/translations/en.json just go to the file and edit it.

**Comment by rsampayo** [comment]
Ill work on blocking the ability to add a Dock Pro twice.

**Comment by mikesalz** [comment]
Yep, I can take care of it
