### ISSUE TITLE
Duplicate Device Entry Allowed in SleepMe Integration Setup

### ISSUE THREAD

**Issue by rsampayo** [rsampayo/sleepme_thermostat#8]
BUG REPORT
During the setup process for the SleepMe integration, it is possible to re-add the same Dock Pro device that has already been added, leading to duplicate entries in the Integration list. The re-added device entry appears with no devices or entities, causing confusion.

Steps to Reproduce:

	1.	Begin setting up the SleepMe integration.
	2.	Select a Dock Pro device that has already been added.
	3.	Proceed with the setup, resulting in a duplicate entry.

Expected Behavior:
The integration setup should prevent users from re-adding a device that has already been configured, or it should recognize the existing entry and avoid creating duplicates.

Actual Behavior:
The setup process allows the same device to be re-added, resulting in a duplicate entry with no devices or entities listed.

Impact:
This behavior may confuse users and clutter the integration entries with unnecessary duplicates, potentially leading to misconfiguration.

**Comment by rsampayo** [comment]
@mikesalz can you 
1.	Delete all devices.
	2.	Restart your system.
	3.	Add one device.
	4.	Turn on the debug log (refresh the page if needed to see the debug button).
	5.	Add your second device.
	6.	Add the same device again (duplicate it).
I have been able to replicate the error.
<img width="998" alt="Screenshot 2024-08-17 at 9 59 19 PM" src="https://github.com/user-attachments/assets/4bc08097-4987-40ad-b6e5-b2a68e642749">

**Comment by mikesalz** [comment]
This is interesting.  I am unable to duplicate the issue again.

**Comment by rsampayo** [comment]
I think this happens when files were modified and the devices were created with earlier version.

**Comment by rsampayo** [comment]
Ill go ahead and close this.
